# SPDX-License-Identifier: GPL-2.0
# Mvebu SoC Family
dtb-$(CONFIG_ARCH_MVEBU) += armada-3720-db.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-3720-espressobin.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-3720-espressobin-512m-emmc.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-3720-espressobin-512m-non-emmc.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-3720-espressobin-1g-emmc.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-3720-espressobin-1g-non-emmc.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-3720-espressobin-2g-emmc.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-3720-espressobin-2g-non-emmc.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-7040-db.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-db.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8040-mcbin.dtb
dtb-$(CONFIG_ARCH_MVEBU) += armada-8080-db.dtb
